# 01_intro
## pandas란?
- 데이터 분석과 조작을 위해 설계된 라이브러리
- 구조화된 데이터(테이블) 처리에 강력한 기능
- 주로 CSV, EXCEL, DB 조회 결과 같은 데이터를 분석할때 사용

In [2]:
import pandas as pd
import numpy as np
pd.__version__

'3.0.1'

## Pandas VS Numpy
- Numpy는 빠른 수치 계산을 위한 도구로 배열 계산에 강하다.
- Pandas는 데이터 분석을 위한 도구로 테이블 형태의 데이터를 다루기 좋다.

In [3]:
arr = np.array([[1,2,3],[4,5,6]])
df = pd.DataFrame(arr,columns=['A','B','C'],index=['row1','row2'])

print(arr)
print()
print(df)

[[1 2 3]
 [4 5 6]]

      A  B  C
row1  1  2  3
row2  4  5  6

## Pandas와 Excel / SQL
- Excel은 사람이 직접 데이터를 수정하고 분석한다.
- Pandas는 코드를 통해 반복 가능한 분석을 수행한다.
- SQL은 DB에서 데이터를 조회하는데 사용한다.
- Pandas는 조회 된 데이터를 가공하고 분석하는데 사용한다.

In [8]:
users = pd.DataFrame(
    {'name' : ['Tom','Jane','Mike'],
     'age' : [25,31,28],
     'city' : ['Seoul','Busan','Incheon']
     }
)
print(users)
print()
print(users[users['age']>30])   # SQL의 where절 처럼 조건으로 행을 필터링

   name  age     city
0   Tom   25    Seoul
1  Jane   31    Busan
2  Mike   28  Incheon

   name  age   city
1  Jane   31  Busan

## 핵심 자료 구조
- Series : 1차원
- DataFrame : 2차원

### Series
Series는 인덱스를 가진 1차원 데이터이다.

In [12]:
scores = pd.Series([85,72,78,95],index=['국어','영어','수학','과학'],name='점수')

print(scores)
print()
print(f'values : {scores.values}')
print(f'index : {scores.index}')
print(f'dtype : {scores.dtype}')
print(f'name : {scores.name}')

국어    85
영어    72
수학    78
과학    95
Name: 점수, dtype: int64

values : [85 72 78 95]
index : Index(['국어', '영어', '수학', '과학'], dtype='str')
dtype : int64
name : 점수

### Series 만들기
리스트, 딕셔너리, 스칼라 값 등으로 만들 수 있다.

In [15]:
s1 = pd.Series([10,20,30])
s2 = pd.Series({'서울':970,'부산':340,'인천':290})
s3 = pd.Series(100,index=['a','b','c'])
print(s1)
print()
print(s2)
print()
print(s3)

0    10
1    20
2    30
dtype: int64

서울    970
부산    340
인천    290
dtype: int64

a    100
b    100
c    100
dtype: int64

## Series 접근
라벨과 위치 둘다 사용할 수 있다.

In [ ]:
temps = pd.Series([23,25,22,28,26],index=['월','화','수','목','금'])

print(temps['수'])      # 라벨
print(temps.iloc[2])    # 위치
print()
print(temps['화':'목']) # 라벨 슬라이싱 (끝 포함)
print(temps.icol[1:4])  # 위치 슬라이ㅣ

22
22

## DataFrame
DataFrame은 핼과 열로 이루어진 2차원 데이블

In [19]:
data = {
    '이름' : ['김철수','이영희','박민수'],
    '나이' : [25,30,28],
    '도시' : ['Seoul','Incehon','Busan']
    }

# 보편적으로 df of list (각 컬럼을 이름을 key로 하고 값으로 리스트를 넣는 구조 많이 사용)
df= pd.DataFrame(data)
df

# list of list : 각행을 리스트로 효현하는 구조
df2 = pd.DataFrame([[1,4],[2,5],[3,6]],columns=['A','B'],index=['row1','row2','row3'])
df2

      A  B
row1  1  4
row2  2  5
row3  3  6

### Dataframe 접근
열, 행 , 셀을 선택하는 기본 패턴 확인

In [ ]:
employees = pd.DataFrame(
    {
        '부서' : ['영업','개발','인사','마케팅'],
        '직급' : ['과장','대리','사원','부장'],
        '급여' : [5000,4000,3000,6000]
    }, index = ['E001','E002','E003','E004']
)

display(employees)

print(employees['부서'])                 # 열 1개 -> Series
print()
print(employees[['부서','직급']])        # 열 여러 개 -> DataFrame
print()
print(employees.loc['E002'])            # 라벨 행 선택 -> Series
print()
print(employees.iloc[0])                # 위치 행 선택 -> Series
print()
print(employees.loc['E003','급여'])     # 셀 선택 -> Scalar

       부서  직급    급여
E001   영업  과장  5000
E002   개발  대리  4000
E003   인사  사원  3000
E004  마케팅  부장  6000

E001     영업
E002     개발
E003     인사
E004    마케팅
Name: 부서, dtype: str

       부서  직급
E001   영업  과장
E002   개발  대리
E003   인사  사원
E004  마케팅  부장

부서      개발
직급      대리
급여    4000
Name: E002, dtype: object

부서      영업
직급      과장
급여    5000
Name: E001, dtype: object

3000

## DataFrame 속성
테이블의 구조를 빠르게 확인할 때 사용한다.

In [27]:
print(f'shape : {employees.shape}')
print(f'columns : {employees.columns}')
print(f'index : {employees.index}')
print()
print(f'dtypes : {employees.dtypes}')

shape : (4, 3)
columns : Index(['부서', '직급', '급여'], dtype='str')
index : Index(['E001', 'E002', 'E003', 'E004'], dtype='str')

dtypes : 부서      str
직급      str
급여    int64
dtype: object

## 데이터 미리보기
자주 쓰는 확인용 메소드

In [ ]:
# 데이터 상위 n개 행 확인 (기본 값 5)
print(employees.head(2))
print()
# 데이터 하위 n개 행 확인
print(employees.tail(2))
print()
# 데이터 전체 구조 요약 확인
# 컬럼 수, 데이터 개수, 결측치 여부, 각 컬럼의 데이터 타입
print(employees.info())
print()
# 수치형 데이터에 대한 통계 요약
# 평균, 표준편차, 최소/최대값
print(employees.describe())

      부서  직급    급여
E001  영업  과장  5000
E002  개발  대리  4000

       부서  직급    급여
E003   인사  사원  3000
E004  마케팅  부장  6000

<class 'pandas.DataFrame'>
Index: 4 entries, E001 to E004
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   부서      4 non-null      str
 1   직급      4 non-null      str
 2   급여      4 non-null      int64
dtypes: int64(1), str(2)
memory usage: 300.0+ bytes
None

                급여
count     4.000000
mean   4500.000000
std    1290.994449
min    3000.000000
25%    3750.000000
50%    4500.000000
75%    5250.000000
max    6000.000000